import axios from 'axios'
import '../styles/globals.css'
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
axios.defaults.withCredentials = true

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
      <script src="https://accounts.google.com/gsi/client"></script>
      </head>
      <body>{children}</body>
    </html>
  )
}
